branches:
  only:
  - master

language: node_js
node_js: 12

matrix:
  include:
  - name: lint
    script:
    - npm run lint
    # Run webpack to check size limits.
    - npx webpack --config config/webpack.prod.js
    after_script:
    - true # don't run codecov

  - name: node
    script:
    - npm run coverageNode

  - name: chrome
    addons:
      chrome: stable
    script:
    - npm run coverageWeb -- --browsers=ChromeHeadless

  - name: firefox
    addons:
      firefox: latest
    script:
    - npm run coverageWeb -- --browsers=FirefoxHeadless

after_script:
- codecov --flags=$TRAVIS_JOB_NAME
