branches:
  only:
  - master

language: node_js

matrix:
  include:
  - name: lint
    node_js: 10
    script:
    - npm run lint
    # Run webpack to check size limits.
    - npx webpack --config config/webpack.prod.js

    - name: node10
    node_js: 10
    script:
    - npm run coverageNode

  - name: node12
    node_js: 12
    script:
    - npm run coverageNode

  - name: chrome
    node_js: 10
    addons:
      chrome: stable
    script:
    - npm run coverageWeb -- --browsers=ChromeHeadless

  - name: firefox
    node_js: 10
    addons:
      firefox: latest
    script:
    - npm run coverageWeb -- --browsers=FirefoxHeadless

after_script:
- codecov --flags=$TRAVIS_JOB_NAME
