language: node_js

matrix:
  include:
  - name: node10
    node_js: 10
    script:
    - npm run lint
    - npm run coverageNode

  - name: node12
    node_js: 12
    script:
    - npm run lint
    - npm run coverageNode

  - name: firefox
    node_js: 10
    addons:
      firefox: latest
    script:
    - npm run coverageWeb

after_script:
- codecov --flags=$TRAVIS_JOB_NAME
